apiVersion: apps/v1
kind: Deployment
metadata:
  name: fixup-twitter-link-deployment
  labels:
    app: fixup-twitter-link
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fixup-twitter-link
  template:
    metadata:
      labels:
        app: fixup-twitter-link
    spec:
      containers:
        - name: fixup-twitter-link
          image: ghcr.io/4m-mazi/fixup-twitter-link:main@sha256:c2c1e8ed35441f2d7c86a3ff9f72597560f938d510bb53f31e100693d80dac30
          envFrom:
            - secretRef:
                name: fixup-twitter-link-secret
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 65532
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              memory: "130Mi"
              cpu: "15m"
