apiVersion: apps/v1
kind: Deployment
metadata:
  name: fixup-twitter-link-deployment
  labels:
    app: fixup-twitter-link
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fixup-twitter-link
  template:
    metadata:
      labels:
        app: fixup-twitter-link
    spec:
      containers:
        - name: fixup-twitter-link
          image: ghcr.io/4m-mazi/fixup-twitter-link:main@sha256:5bc989fbf10d6c735660a5502cc1646c334c35c9e5d26b9c44f4ff2927df6df4
          envFrom:
            - secretRef:
                name: fixup-twitter-link-secret
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 65532
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              memory: "130Mi"
              cpu: "15m"
