apiVersion: apps/v1
kind: Deployment
metadata:
  name: osekkai-chan-deployment
  labels:
    app: osekkai-chan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osekkai-chan
  template:
    metadata:
      labels:
        app: osekkai-chan
    spec:
      containers:
        - name: osekkai-chan
          image: ghcr.io/4m-mazi/osekkai-chan:0.1.35@sha256:9729238b4dd8165f0a6d9ff95cbec1b9ada2eec7d1d8c8428d39fd135d08e057
          env:
            - name: ROLE_ID
              value: "1167009278368940032"
            - name: VOICE_CHANNEL_ID
              value: "1185980820813529228"
            - name: TEXT_CHANNEL_ID
              value: "1167011473327915078"
          envFrom:
            - secretRef:
                name: osekkai-chan-secret
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
